# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Create-ActionsPR

on:
 workflow_dispatch:
    branches:
      - main
    
jobs:
  build:
    
    runs-on: ubuntu-latest
        
    steps: 
      - name: Checkout code to runner
        uses: actions/checkout@v2
      
      - run: |
          dir
          
        shell: pwsh
